apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: o11y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o11y
    app.kubernetes.io/part-of: o11y
  name: o11y
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: o11y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: o11y
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/o11y/o11y@sha256:525b46f49803da41f5307525720c8ba3143fe868c347de85b51a880dd73e0181
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
