apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: o11y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/o11y/o11y@sha256:b703fbd24a95537adb07d6c9206607638bbaccbfba10d511fb683afc39c82b91
        name: container-image
        resources: {}
status: {}
