apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: o11y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o11y
    app.kubernetes.io/part-of: o11y
  name: o11yonzf
spec:
  port:
    targetPort: 8090
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: o11y
    weight: 100
status: {}
